/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCYLEONOR
 */
public class Inmobiliaria extends javax.swing.JFrame {

    /**
     * Creates new form Inmobiliaria
     */
    public Inmobiliaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCI = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCF = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inmobiliaria");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Inmobiliaria");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("Metros Cuadrados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMKeyTyped(evt);
            }
        });
        jPanel1.add(txtM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Cuota Inicial");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblCI.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("Monto por cuota");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        lblCF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 140, 40));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        cmdRestaurar.setText("Restaurar");
        cmdRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        
        if (txtM.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Ha Ingresado Los Metros Cuadrados", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtM.requestFocusInWindow();
        } else if (txtM.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "Ingrese Una Longitud Superior a 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtM.selectAll();
            txtM.requestFocusInWindow();
        } else {

            String r, re;
            double m, ci, cf, t;

            m = Double.parseDouble(txtM.getText());

            t = m * 80000;

            ci = t * 0.35;

            cf = (t - ci) / 12;

            r = String.valueOf(ci);
            re = String.valueOf(cf);

            lblCI.setText("$ " + r);
            lblCF.setText("$ " + re);

        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaurarActionPerformed

        txtM.setText("");
        lblCI.setText("");
        lblCF.setText("");
        txtM.requestFocusInWindow();

    }//GEN-LAST:event_cmdRestaurarActionPerformed

    private void txtMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtM.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Ha Ingresado Los Metros Cuadrados", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtM.requestFocusInWindow();
            } else if (txtM.getText().equalsIgnoreCase("0")) {
                JOptionPane.showMessageDialog(this, "Ingrese Una Longitud Superior a 0", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtM.selectAll();
                txtM.requestFocusInWindow();
            } else {

                String r, re;
                double m, ci, cf, t;

                m = Double.parseDouble(txtM.getText());

                t = m * 80000;

                ci = t * 0.35;

                cf = (t - ci) / 12;

                r = String.valueOf(ci);
                re = String.valueOf(cf);

                lblCI.setText("$ " + r);
                lblCF.setText("$ " + re);
            }
        }
    }//GEN-LAST:event_txtMKeyPressed

    private void txtMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inmobiliaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCF;
    private javax.swing.JLabel lblCI;
    private javax.swing.JTextField txtM;
    // End of variables declaration//GEN-END:variables
}
